fix: Add required download_folder parameter to NSE initialization
NSE library requires download_folder argument in __init__.
Added parameter with default './data/nse_downloads' and create
directory if it doesn't exist.

Fixes TypeError: NSE.__init__() missing 1 required positional argument